# Google Cloud Build configuration for deploying documentation to Cloud Run
#
# Can be run from project root or developer_documentation directory:
#   From root: gcloud builds submit --config=developer_documentation/cloudbuild.yaml .
#   From docs: cd developer_documentation && gcloud builds submit --config=cloudbuild.yaml .

substitutions:
  _SERVICE_NAME: cdp-docs
  _REGION: europe-west1
  _IMAGE_NAME: cdp-docs

steps:
  # Build Docker image (runs in developer_documentation directory)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    dir: 'developer_documentation'  # Change working directory for this step
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 2: Push the tagged image (with commit SHA)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-sha'
    waitFor: ['build-image']
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-latest'
    waitFor: ['build-image']
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    waitFor: ['push-image-sha']
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

# Images to be stored in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1200s'  # 20 minutes

